package database

const UserSchema = `
	CREATE TABLE IF NOT EXISTS users (
		id UUID PRIMARY KEY,
		name VARCHAR(225) NOT NULL, 
		email VARCHAR(225) NOT NULL,
		password VARCHAR(225) NOT NULL,
		created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
	);
`
